title: Not a Senior's blog
email: NotASeniorDev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A little blog, with a few posts, so maybe I can help someone on its path.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://NotASenior.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: NotASeniorDev
github_username:  NotASenior

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: pages-themes/cayman@v0.2.0
